# referenced https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html
{% set name = "q2-winnowing" %}
{% set version = "20.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

# no binaries include so files are architecture-independent
build:
  noarch: generic

# Add bioconda channel for biom
extra:
  channels:
    - conda-forge
    - bioconda

requirements:
  host:
    - pip
    - python=3.6
    - setuptools
  run:
    - python=3.6
    # Qiime2 modules
    - qiime2 >=2019.1
    - q2-types
    # Other modules
    - biom-format
    - minepy
    - seaborn
    - matplotlib
    - networkx
    - scipy
    - pandas
    - numpy
    - rpy2

test:
  imports:
    - minepy
    - rpy2

about:
  home: https://github.com/ldb385/q2-winnowing
  license: BSD
  license_family: BSD
